apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-deployment
  namespace: monprojet1
  labels:
    app: nginx-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-rpc
        image: nginx:latest
        ports:
        - containerPort: 8080