apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: nginx-replicaset
  namespace: monprojet1
  labels:
    app: nginx-replicaset

spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset
    spec:
      containers:
      - name: nginx-rpc
        image: nginx:latest
        ports:
        - containerPort: 80