apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: nginx-expose-pod

spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: nginx-expose-pod