apiVersion: v1

kind: Pod

metadata:
  name: pod-nginx
  labels:
    app: nginx
    env: test

spec:
  containers:
  - name: c-nginx
    image: nginx:latest
    ports: 
     - containerPort: 80
    resources:
      requests:
        cpu: 0.5
        memory: "50Mi"
      limits:
        cpu: 1
        memory: "200Mi"
