apiVersion: v1

kind: LimitRange

metadata:
  name: my-limitrange
  
spec:
  limits:
    - type: Container
      max:
        memory: "512Mi"  # Limite maximale de mémoire par conteneur
        cpu: "1"         # Limite maximale de CPU par conteneur
      min:
        memory: "64Mi"   # Demande minimale de mémoire par conteneur
        cpu: "0.1"       # Demande minimale de CPU par conteneur
      default:
        memory: "256Mi"  # Valeur par défaut pour la mémoire
        cpu: "0.5"       # Valeur par défaut pour le CPU
      defaultRequest:
        memory: "128Mi"  # Demande par défaut de mémoire
        cpu: "0.2"       # Demande par défaut de CPU